#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["GestionPedidosService.Api/GestionPedidosService.Api.csproj", "GestionPedidosService.Api/"]
COPY ["GestionPedidosService.Business/GestionPedidosService.Business.csproj", "GestionPedidosService.Business/"]
COPY ["GestionPedidosService.Persistence/GestionPedidosService.Persistence.csproj", "GestionPedidosService.Persistence/"]
COPY ["GestionPedidosService.Domain/GestionPedidosService.Domain.csproj", "GestionPedidosService.Domain/"]
RUN dotnet restore "GestionPedidosService.Api/GestionPedidosService.Api.csproj"
COPY . .
WORKDIR "/src/GestionPedidosService.Api"
RUN dotnet build "GestionPedidosService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GestionPedidosService.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
ENTRYPOINT ["dotnet", "GestionPedidosService.Api.dll"]